---
# Install the necessary packages
- name: Install package requirements for bookstack
  apt:
    name:
      - git 
      - unzip 
      - apache2 
      - php8.1
      - curl 
      - php8.1-curl 
      - php8.1-mbstring 
      - php8.1-ldap
      - php8.1-xml
      - php8.1-zip 
      - php8.1-gd
      - php8.1-mysql 
      - mysql-server-8.0 
      - libapache2-mod-php8.1
      - composer
    update_cache: true
  become: true
  tags:
    - git
    - bookstack
    - apache

# Clone the bookstack repository
- name: Clone BookStack repository
  git:
    repo: https://github.com/BookStackApp/BookStack.git
    dest: "{{ BOOKSTACK_DIR }}"
    version: "v21.05.3"
    depth: 1
    single_branch: true
  tags:
    - git
    - bookstack


# Install the bookstack dependencies with Composer.
- name: Install BookStack Composer dependencies
  command: php /usr/bin/composer install --no-dev --no-plugins
  args:
    chdir: "{{ BOOKSTACK_DIR }}"
  tags:
    - bookstack


# Copy .env file from template
- name: create .env file from template
  template:
    src: env.j2
    dest: "{{ BOOKSTACK_DIR }}/.env"
    owner: root
    group: www-data
    mode: 0644
  tags:
    - bookstack


# Generate application key
- name: generate application key
  shell: |
    cd {{ BOOKSTACK_DIR }}
    php artisan key:generate --no-interaction --force
    php artisan migrate --no-interaction --force
  become: true
  tags:
    - bookstack

# Change file permissions in bookstack directory
- name: change permissions
  shell: |
    cd {{ BOOKSTACK_DIR }}
    chown -R root:www-data ./
    chmod -R 755 ./
    chmod -R 775 bootstrap/cache public/uploads storage
    git config core.fileMode false
  become: true
  tags:
    - git

# Enable apache modules
- name: enable apache modules
  apache2_module:
    state: present
    name: "{{ item }}"
  loop:
    - rewrite
    - headers
  tags:
    - apache
    - bookstack


# Create apache config file from template
- name: create apache config
  template:
    src: bookstack.conf.j2
    dest: /etc/apache2/sites-available/bookstack.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - apache
    - bookstack


# Enable the bookstack apache config
- name: disable default apache config and enable bookstack conf
  shell: |
    a2dissite 000-default.conf
    a2ensite bookstack.conf
  become: true
  tags:
    - apache

# Restart apache service
- name: Restart Apache service
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true
  tags:
    - apache
